
echo -e "      ╭"
echo -e "      │○ Take a shower"
echo -e "      │\e[32m● \e[9mWater plants\e[m"
echo -e "      │○ Give myself some sunshine"
echo -e "      │    I've needing more D-vitamine"
echo -e "      │    At least I guess so, I'm wetto asf"
echo -e "      │"
echo -e "      │\e[32m● \e[9mBuy chips\e[m"
echo -e "      │"
echo -e "      │"
echo -e "11:00 ○ Scriptures Study"
echo -e "11:15 │"
echo -e "      │"
echo -e "\e[34m12:00 ● \e[9mLunch\e[m"
echo -e "      │"
echo -e "12:15 ├ It's a note I took in the afternoon"
echo -e "      │ after noticing I needed to take a"
echo -e "      │ note about what happened today"
echo -e "      │"
echo -e "13:00 ○ Math Study"
echo -e "      │   Some description for my math class"
echo -e "      │   this is a course I purchased yey"
echo -e "      │"
echo -e "15:00 \e[31m✖ \e[9mPortuguese Study\e[m"
echo -e "      │\e[31m-\e[m  The teacher canceled for some illness"
echo -e "      │"
echo -e "      ╰"
